### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by JoSchmaltz** [raphaelreme/tps#5] opened 2024-09-08 14:21 UTC
I want to use this to warp 2d vector images (svg). I believe I understand the process as described for scikit [here](https://scikit-image.org/docs/stable/auto_examples/transform/plot_tps_deformation.html), but why is the numpy array for the control point  X_c in the [getting started code](https://github.com/raphaelreme/tps/blob/main/README.md#getting-started) a 3D array and the target ndarray 2D? 
I expected both control and target to have the same dimension?
Apologies, certainly a newbie here - and I dort even know if this is the place to ask.

**Comment by raphaelreme** [comment] 2024-09-08 17:34
Hi !

It was just to show an example where the source space dimension (d_s) is different than the target space dimension (d_t), but you can look at the examples inside the `example` folder, you will see a 1d and 2d code, plus one for image warping.

In your case you will have d_s = d_t = 2. You can first generate a random transformation (calling `fit` on random control points, as done in the example for image warping), then you need to apply it to any element of your svg.

But this is not that easily done depending on the number of features you wanna support (i'm not so much familiar with the format, but if i'm not mistaken it can be quite complexe with some nested images & svg). But i guess that as a start, you can quite easily warp any polygons by warping the 2d positions of each vertex.

Let me know if this helps ;)

**Comment by JoSchmaltz** [comment] 2024-09-10 21:05
That's great, thanks, I should have figured this out myself. I have managed to recreate something very similar to this (taken from [here](https://khanhha.github.io/posts/Thin-Plate-Splines-Warping/)) with _vectors_ or more specifically a geopandas dataframe instead of an image as in the examples. 

![Screenshot 2024-09-10 214513](https://github.com/user-attachments/assets/8f11bbf2-a53e-4fc4-9452-60e204fb9194)
With that I achieve my main objective which is to warp a [OSM map](https://www.openstreetmap.org/), 
However, I am wondering (and this is probably more a algorithmic question than one for this repository) if there is a parameter that defined how "rigid" the structure is. I understand the control points will move to the target points with the alpha parameter defining how "exact". I also understand that points outside the control points will move subject to their distance to all control->target vectors. But how far will these points move? Is there a parameter that defines the how strong the reduction of "pull" from the c->t vectors is with increasing distance from these vectors? Sorry for my un mathematical lingo, but i am looking at this more with artistic intentions and little mathematical background.
Thank you!

**Comment by raphaelreme** [comment] 2024-09-10 23:35
Great to hear !

Sadly I'm no expert on the mathematical background neither, so I may not be aware of some other solutions that could already exist to control this "rigidity". This being said, here are some infos and tricks that may help you reach what you want:
1. alpha should more be seen as a control of the smoothness of the solution. It allows to relax the constraints to get a more simple solution (meaning that for an increased smoothness of the deformation, the control points are allowed not to be warped perfectly). I didn't check, and I may be wrong, but i think that the higher the regularization alpha, the more the deformation tends to be linear and thus rigid.
2. Another way to improve the resulting deformation is to better sample the control points. The estimated deformation is much less "precise" at location where no control point is found in the neighborhood. This is only an elastic interpolation method, so it is unable to predict a correct deformation outside of the control points domain and between control points it will predict a smooth elastic interpolation. Therefore I would advise to have at least control points in the corners (and borders ?) of your image, and also at least one for each deformation inside the image that you want to model.

Hope this helps!

**Comment by JoSchmaltz** [comment] 2024-09-19 08:29
For what it's worth: a parameter to control the rigidity of the deformation seems to exist in the TPS concept:

[The smoothing variant, correspondingly, uses a tuning parameter λ to control the rigidity of the deformation, balancing the aforementioned criterion with the measure of goodness of fit, thus minimizing.](https://en.m.wikipedia.org/wiki/Thin_plate_spline)

I suspect this parameters exists somewhere in the code of this library. I will attempt to expose it such that it can be controlled easily.

**Comment by raphaelreme** [comment] 2024-09-19 08:43
Yes this $\lambda$ in wikipedia is the parameter $\alpha$ in the code ;)

It allows you to control the regularization <=> rigidity (cf my previous message (1), it seems to be confirmed by what wikipedia says)

**Comment by raphaelreme** [comment] 2024-10-03 09:42
I'm closing this issue. Do not hesitate to reopen it if needed ;)

**Closed as completed by raphaelreme** 2024-10-03 09:42 UTC
